base:
    dns: 127.0.0.1
    dns_search:
     - node.consul
    environment:
    - DC_NAME=dc1

hbase:
    extends:
      file: base.yml
      service: base
    image: qnib/alpn-hbase

hdfs:
    extends:
      file: base.yml
      service: base
    image: qnib/alpn-hdfs
