consul:
    hostname: consul
    container_name: consul
    image: qnib/alpn-consul
    environment:
    - DC_NAME=dc1
    - RUN_SERVER=true
    - BOOTSTRAP_CONSUL=true
    ports:
    - "8500:8500"
    dns: 127.0.0.1

zkui:
    hostname: zkui
    container_name: zkui
    extends:
      file: base.yml
      service: base
    image: qnib/alpn-zkui
    links:
    - consul:consul
    ports:
    - 9090:9090
    privileged: true

zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: qnib/alpn-zookeeper
    extends:
      file: base.yml
      service: base
    environment:
    - SERVERS=zookeeper.node.dc1.consul
    links:
    - consul:consul
    ports:
    - 2181:2181
    privileged: true

hdfs-namenode:
    hostname: hdfs-namenode
    container_name: hdfs-namenode
    extends:
      file: base.yml
      service: hdfs
    environment:
     - HADOOP_HDFS_NAMENODE=true
     - HADOOP_HDFS_DATANODE=false
    links:
     - consul:consul
    ports:
     - 8020:8020
     - 50070:50070

hbase:
    hostname: hbase
    container_name: hbase
    extends:
      file: base.yml
      service: hbase
    environment:
     - HADOOP_HDFS_NAMENODE=false
     - HBASE_MASTER=true
     - HBASE_REGIONSERVER=true
     - HBASE_REST=true
    links:
     - consul:consul
    ports:
     - 16000
     - 16010
     - 16020
     - 16030
     - 16070
     - 16080

hbase-data1:
    hostname: hbase-data1
    container_name: hbase-data1
    extends:
      file: base.yml
      service: hbase
    environment:
     - HBASE_MASTER=false
     - HBASE_REST=true
     - HBASE_REGIONSERVER=true
    links:
     - consul:consul
    ports:
     - 16020
     - 16030
     - 16070
     - 16080

hbase-data2:
    hostname: hbase-data2
    container_name: hbase-data2
    extends:
      file: base.yml
      service: hbase
    environment:
     - HBASE_REST=true
     - HBASE_MASTER=false
     - HBASE_REGIONSERVER=true
    links:
     - consul:consul
    ports:
     - 16020
     - 16030
     - 16070
     - 16080

